# Generated by Django 3.0.2 on 2020-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], default='P', max_length=1, verbose_name='Status')),
                ('bank_name', models.CharField(max_length=16, verbose_name='Bank')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('redirect_after_success', models.CharField(editable=False, max_length=255)),
                ('redirect_on_failure', models.CharField(editable=False, max_length=255)),
                ('raw_response', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=16, verbose_name='bank')),
                ('description', models.CharField(help_text='reference description', max_length=255, verbose_name='reference description')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'pending'), ('F', 'failed'), ('C', 'completed')], default='P', max_length=1, verbose_name='status')),
                ('redirect_after_success', models.CharField(editable=False, max_length=255)),
                ('redirect_on_failure', models.CharField(editable=False, max_length=255)),
            ],
        ),
    ]
